{
    'name': 'Hiworth Human resource attendance',
    'description': 'Modifies default attendnace view',
    'author': 'hiworth',
    'depends': [
                'base',
                'product',
                'account',
                'hr_attendance',
                'hr_holidays',
                'hr_payroll',
                'stock'
                ],
    'data': [
        'security/ir.model.access.csv',
        # 'security/ir.rule.csv',
        'report/hiworth_hr_leave.xml',
        'report/attendance_individual.xml',
        'report/daily_report.xml',
        'report/payslip_batches_report_view.xml',
        'report/individual_payslip_report_views.xml',
        'wizard/payroll_entry_wizard_views.xml',
        'wizard/salary_rule_history_wizard_views.xml',
        'wizard/statutory_payment_wizard_views.xml',
        'view/web_export_view.xml',
        'view/exgratia_payment_views.xml',
        'view/hr_contract.xml',
        'view/hiworth_hr_attendance.xml',
        'view/hiworth_hr_leave.xml',
        'view/hr_holidays.xml',
        # 'view/hiworth_hr_attendance_wizard.xml',
        # 'data/defaultdata.xml',
        'view/report_payslip.xml',
        'view/report_payslipdetails.xml',
        'view/hr_employee_view.xml',
        'view/attendance_today.xml',
        'view/res_users.xml',
        'view/attendance_request.xml',
        'view/sequences.xml',
        'view/daily_wages.xml',
        'security/hide_menu.xml',
        'report/worker_wage.xml',
        # 'view/job_title.xml',
        # 'report/id_card.xml',
        'view/employee_attendance_new.xml',
        'view/hr_insurance.xml',
        'view/resigned_employee_view.xml',
        'data/data.xml',
        'report/employee_report.xml',
        'report/insurance_report_view.xml',
        'report/pf_esi_report.xml',
        'wizard/compute_sheet_wizard_views.xml',
        'wizard/absentees_report_views.xml',
        'report/payroll_report_views.xml',
        'wizard/insurance_renewal_report_wizard_views.xml',
        'view/professional_tax_views.xml',
        'view/labour_welfare_fund_views.xml',
        'report/pt_report_views.xml',
        'report/esi_report_views.xml',
        'report/labour_welfare_fund_views.xml',
        'view/hr_payslip_run_views.xml',
        'view/employee_payroll_info_views.xml',
        'view/salary_advance.xml',
    ]
}
